name: Clean up workflow
on:
  push:
    branches:
      - master
jobs:
    clean:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Clean up workflow
          uses: benjithatfoxguy/github-workflow-clean-action@v1
          with:
                delete-level: 'repo'
                token: ${{ secrets.GH_TOKEN }}
                owner: ${{ github.repository_owner }}
                repo: ${{ github.event.repository.name }}
                workflow: 'Purge History'        