name: Test Delete Workflow
on:
  push:
    branches:
      - master
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          echo "Hello, World!"